coverage:
  status:
    project:
      default:
        # basic
        target: 80%
        threshold: 15%
        base: auto 
        flags: 
          - unit
        paths: 
          - "src"
        # advanced settings
        branches: 
          - main
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
    
    patch:
      default:
      # basic
      target: 80%
      threshold: 15%
      base: auto 
      flags: 
        - unit
      paths: 
        - "src"
      # advanced settings
      branches: 
        - main
      if_ci_failed: error #success, failure, error, ignore
      informational: false
      only_pulls: false

