"""Removing column

Revision ID: 081ed5db22c1
Revises: 908b0991fb3f
Create Date: 2022-06-25 13:13:27.271780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081ed5db22c1'
down_revision = '908b0991fb3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
