"""Testing

Revision ID: 357404079b21
Revises: fca238ba7670
Create Date: 2022-06-25 14:01:52.725469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357404079b21'
down_revision = 'fca238ba7670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('price_reais', sa.Integer(), nullable=False))
    op.add_column('item', sa.Column('price_cents', sa.Integer(), nullable=False))
    op.add_column('item', sa.Column('stock', sa.Integer(), nullable=False))
    op.add_column('item', sa.Column('sale', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'sale')
    op.drop_column('item', 'stock')
    op.drop_column('item', 'price_cents')
    op.drop_column('item', 'price_reais')
    # ### end Alembic commands ###
