"""Alterando db

Revision ID: 40f0dbaf3226
Revises: 
Create Date: 2022-06-26 11:50:28.811778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f0dbaf3226'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('expiration_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('budget_reais', sa.Integer(), nullable=False),
    sa.Column('budget_cents', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('seller_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price_reais', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('sale', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('expiration_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('seller_id', sa.String(), nullable=False),
    sa.Column('buyer_id', sa.String(), nullable=False),
    sa.Column('cart_id', sa.String(), nullable=False),
    sa.Column('shipping_cost_reais', sa.Integer(), nullable=True),
    sa.Column('shipping_cost_cents', sa.Integer(), nullable=True),
    sa.Column('items_cost_reais', sa.Integer(), nullable=False),
    sa.Column('items_cost_cents', sa.Integer(), nullable=False),
    sa.Column('total_cost_reais', sa.Integer(), nullable=False),
    sa.Column('total_cost_cents', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_item',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('cart_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id', 'item_id', 'cart_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_item')
    op.drop_table('transaction')
    op.drop_table('session')
    op.drop_table('item')
    op.drop_table('user')
    op.drop_table('cart')
    # ### end Alembic commands ###
