"""Testing

Revision ID: 9a6b551b0ff1
Revises: 357404079b21
Create Date: 2022-06-25 14:08:26.873142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a6b551b0ff1'
down_revision = '357404079b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('budget_reais', sa.INTEGER(), nullable=False),
    sa.Column('budget_cents', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('item',
    sa.Column('item_id', sa.VARCHAR(), nullable=False),
    sa.Column('seller', sa.VARCHAR(), nullable=True),
    sa.Column('price_reais', sa.INTEGER(), nullable=False),
    sa.Column('price_cents', sa.INTEGER(), nullable=False),
    sa.Column('stock', sa.INTEGER(), nullable=False),
    sa.Column('sale', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['seller'], ['user.username'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###
