"""Adding table

Revision ID: b01546ccca76
Revises: 081ed5db22c1
Create Date: 2022-06-25 13:17:02.512526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b01546ccca76'
down_revision = '081ed5db22c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('budget_reais', sa.INTEGER(), nullable=False),
    sa.Column('budget_cents', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###
